targets:
  OBAKit:
    type: framework
    platform: iOS
    sources: ["."]
    dependencies:
      - target: OBAKitCore
      - package: BLTNBoard
      - package: Hyperconnectivity
      - package: Eureka
      - package: FloatingPanel
      - package: MarqueeLabel
    postBuildScripts:
      - path: "../scripts/swiftlint.sh"
        name: Swiftlint
    scheme:
      gatherCoverageData: true
    info:
      path: "Info.plist"
      properties:
        CFBundleShortVersionString: 20.3.0
    settings:
      base:
        APPLICATION_EXTENSION_API_ONLY: false
      configs:
          Debug:
            LD_RUNPATH_SEARCH_PATHS:
              - "$(inherited)"
              - "@executable_path/Frameworks"
          Release:
            LD_RUNPATH_SEARCH_PATHS:
              - "$(inherited)"
              - "@executable_path/Frameworks"
