name: OBAKit
options:
  bundleIdPrefix: org.onebusaway
targets:
  DemoApp:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    sources: [DemoApp]
    dependencies:
      - target: OBAKit
      - carthage: SwiftProtobuf
  OBAKit:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [Application, Location, Models, Network]
    dependencies:
      - carthage: SwiftProtobuf
      - carthage: CocoaLumberjack
      - carthage: CocoaLumberjackSwift
  OBAKitTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "11.0"
    sources: [OBAKitTests]
    dependencies:
      - target: DemoApp
      - carthage: Nimble
      - carthage: OHHTTPStubs