name: OBAKit
options:
  bundleIdPrefix: org.onebusaway
targets:
  OneBusAway:
    type: application
    platform: iOS
    deploymentTarget: "12.3"
    sources: [DemoApp]
    dependencies:
      - target: OBAKit
      - carthage: SwiftProtobuf
    info:
      path: DemoApp/Info.plist
      properties:
        DeepLinkServerBaseAddress: "http://alerts.onebusaway.org"
        LSApplicationQueriesScheme: [fb, twitter, comgooglemaps, fb313213768708402HART, org.sdmts.riderapp.compassmobile.payments, co.bytemark.tgt]
        LSRequiresIPhoneOS: true
        NSUserActivityTypes:
          - org.onebusaway.OneBusAway.user_activity.stop
          - org.onebusaway.OneBusAway.user_activity.trip
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        NSLocationAlwaysAndWhenInUseUsageDescription: Show your location on the map
        NSLocationWhenInUseUsageDescription: Show your location on the map
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    scheme:
      gatherCoverageData: true
  OBAKit:
    type: framework
    platform: iOS
    deploymentTarget: "12.3"
    sources: [Application, Location, Models, Network, TripPlanning]
    dependencies:
      - carthage: AloeStackView
      - carthage: CocoaLumberjack
      - carthage: CocoaLumberjackSwift
      - carthage: Eureka
      - carthage: FloatingPanel
      - carthage: IGListKit
      - carthage: SVProgressHUD
      - carthage: SwiftProtobuf
      - carthage: SwipeCellKit
    postBuildScripts:
      - path: scripts/swiftlint.sh
        name: Swiftlint
    scheme:
      gatherCoverageData: true
  OBAKitTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "12.3"
    sources: [OBAKitTests]
    dependencies:
      - target: OneBusAway
      - carthage: Nimble
      - carthage: OHHTTPStubs