name: OBAKit
options:
  bundleIdPrefix: org.onebusaway
targets:
  DemoApp:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    sources: [DemoApp]
    dependencies:
      - target: OBAKit
      - carthage: SwiftProtobuf
    info:
      path: DemoApp/Info.plist
      properties:
        DeepLinkServerBaseAddress: "http://alerts.onebusaway.org"
        LSRequiresIPhoneOS: true
        NSUserActivityTypes:
          - org.onebusaway.DemoApp.user_activity.stop
          - org.onebusaway.DemoApp.user_activity.trip
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        NSLocationAlwaysAndWhenInUseUsageDescription: Show you your location on the map
        NSLocationWhenInUseUsageDescription: Show you your location on the map
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
  OBAKit:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [Application, Location, Models, Network]
    dependencies:
      - carthage: AloeStackView
      - carthage: CocoaLumberjack
      - carthage: CocoaLumberjackSwift
      - carthage: FloatingPanel
      - carthage: IGListKit
      - carthage: SwiftProtobuf
    postBuildScripts:
      - path: scripts/swiftlint.sh
        name: Swiftlint
    scheme:
      gatherCoverageData: true
  OBAKitTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "11.0"
    sources: [OBAKitTests]
    dependencies:
      - target: DemoApp
      - carthage: Nimble
      - carthage: OHHTTPStubs