name: OBAKit

options:
  bundleIdPrefix: org.onebusaway

targets:
  OBADemo:
    type: application
    platform: iOS
    deploymentTarget: "12.3"
    sources: [Apps/DemoApp]
    dependencies:
      - target: OBAKit
      - carthage: SwiftProtobuf
      - framework: FIRAnalyticsConnector.framework
        embed: false
      - framework: FirebaseAnalytics.framework
        embed: false
      - framework: FirebaseCore.framework
        embed: false
      - framework: FirebaseCoreDiagnostics.framework
        embed: false
      - framework: FirebaseInstanceID.framework
        embed: false
      - framework: GoogleAppMeasurement.framework
        embed: false
      - framework: GoogleUtilities.framework
        embed: false
      - framework: nanopb.framework
        embed: false
    info:
      path: Apps/DemoApp/Info.plist
      properties:
        AppDevelopersEmailAddress: iphone-app@onebusaway.org
        DeepLinkServerBaseAddress: http://alerts.onebusaway.org
        PrivacyPolicyURL: http://onebusaway.org/privacy/
        CFBundleDisplayName: OBADemo
        LSApplicationQueriesScheme: [fb, twitter, comgooglemaps, fb313213768708402HART, org.sdmts.riderapp.compassmobile.payments, co.bytemark.tgt]
        LSRequiresIPhoneOS: true
        NSHumanReadableCopyright: "© Open Transit Software Foundation"
        NSUserActivityTypes:
          - org.onebusaway.demoapp.user_activity.stop
          - org.onebusaway.demoapp.user_activity.trip
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        NSLocationAlwaysAndWhenInUseUsageDescription: Show your location on the map
        NSLocationWhenInUseUsageDescription: Show your location on the map
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    scheme:
      gatherCoverageData: true
    settings:
      base:
        FRAMEWORK_SEARCH_PATHS: "$(inherited) $(PROJECT_DIR)/Apps/Shared/FirebaseAnalytics"
        PRODUCT_BUNDLE_IDENTIFIER: org.onebusaway.demoapp
        OTHER_LDFLAGS: -ObjC
  OBAKit:
    type: framework
    platform: iOS
    deploymentTarget: "12.3"
    sources: [Application, Location, Models, Network, TripPlanning]
    dependencies:
      - carthage: AloeStackView
      - carthage: CocoaLumberjack
      - carthage: CocoaLumberjackSwift
      - carthage: Eureka
      - carthage: FloatingPanel
      - carthage: IGListKit
      - carthage: SVProgressHUD
      - carthage: SwiftProtobuf
      - carthage: SwipeCellKit
    postBuildScripts:
      - path: scripts/swiftlint.sh
        name: Swiftlint
    scheme:
      gatherCoverageData: true
  OBAKitTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "12.3"
    sources: [OBAKitTests]
    dependencies:
      - target: OBADemo
      - carthage: Nimble
      - carthage: OHHTTPStubs