name: OBAKit

options:
  bundleIdPrefix: org.onebusaway

targets:
  App:
    type: application
    platform: iOS
    deploymentTarget: "12.4"
    sources: [Apps/OneBusAway]
    dependencies:
      - target: OBAKitCore
      - target: OBAKit
      - carthage: SwiftProtobuf
      - framework: FIRAnalyticsConnector.framework
        embed: false
      - framework: FirebaseAnalytics.framework
        embed: false
      - framework: FirebaseCore.framework
        embed: false
      - framework: FirebaseCoreDiagnostics.framework
        embed: false
      - framework: FirebaseInstanceID.framework
        embed: false
      - framework: GoogleAppMeasurement.framework
        embed: false
      - framework: GoogleUtilities.framework
        embed: false
      - framework: nanopb.framework
        embed: false
      - framework: Fabric.framework
        embed: false
      - framework: Crashlytics.framework
        embed: false
    attributes:
      SystemCapabilities:
        com.apple.Push:
          enabled: 1
    entitlements:
      path: Apps/OneBusAway/OneBusAway.entitlements
      properties:
        com.apple.security.application-groups:
          - group.org.onebusaway.iphone
        aps-environment: development
        com.apple.developer.associated-domains:
          - applinks:onebusaway.co
          - applinks:www.onebusaway.co
          - applinks:alerts.onebusaway.org
    info:
      path: Apps/OneBusAway/Info.plist
      properties:
        OBAKitConfig:
          AppDevelopersEmailAddress: iphone-app@onebusaway.org
          DeepLinkServerBaseAddress: http://alerts.onebusaway.org
          PrivacyPolicyURL: http://onebusaway.org/privacy/
          PushNotificationAPIKey: d5d0d28a-6091-46cd-9627-0ce01ffa9f9e
          RESTServerAPIKey: org.onebusaway.iphone
          RegionsServerBaseAddress: http://regions.onebusaway.org
        CFBundleDisplayName: OneBusAway
        LSApplicationQueriesSchemes: [fb, twitter, comgooglemaps, fb313213768708402HART, org.sdmts.riderapp.compassmobile.payments, co.bytemark.tgt]
        LSRequiresIPhoneOS: true
        NSHumanReadableCopyright: "© Open Transit Software Foundation"
        NSUserActivityTypes:
          - org.onebusaway.iphone.user_activity.stop
          - org.onebusaway.iphone.user_activity.trip
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        NSLocationAlwaysAndWhenInUseUsageDescription: Show your location on the map
        NSLocationWhenInUseUsageDescription: Show your location on the map
        UIBackgroundModes: [remote-notification]
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities: [armv7]
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    postBuildScripts:
      - { name: Crashlytics, script: "${PROJECT_DIR}/Apps/Shared/Crashlytics/Fabric.framework/run", inputFiles: ["$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)"], runOnlyWhenInstalling: true }
    scheme:
      gatherCoverageData: true
    settings:
      base:
        FRAMEWORK_SEARCH_PATHS: "$(inherited) $(PROJECT_DIR)/Apps/Shared/FirebaseAnalytics $(PROJECT_DIR)/Apps/Shared/Crashlytics"
        PRODUCT_BUNDLE_IDENTIFIER: org.onebusaway.iphone
        OTHER_LDFLAGS: -ObjC
  OBAKitCore:
    type: framework
    platform: iOS
    deploymentTarget: "12.4"
    sources: [OBAKitCore]
    dependencies:
      - carthage: CocoaLumberjack
      - carthage: CocoaLumberjackSwift
      - carthage: SwiftProtobuf
    postBuildScripts:
      - { path: "scripts/swiftlint.sh", name: Swiftlint }
    scheme:
      gatherCoverageData: true
    settings:
      base:
        APPLICATION_EXTENSION_API_ONLY: true
  OBAKit:
    type: framework
    platform: iOS
    deploymentTarget: "12.4"
    sources: [OBAKit, TripPlanning]
    dependencies:
      - target: OBAKitCore
      - carthage: AloeStackView
      - carthage: BLTNBoard
      - carthage: CocoaLumberjack
      - carthage: CocoaLumberjackSwift
      - carthage: Connectivity
      - carthage: Eureka
      - carthage: FloatingPanel
      - carthage: IGListKit
      - carthage: MarqueeLabel
      - carthage: OneSignal
      - carthage: SVProgressHUD
      - carthage: SwiftProtobuf
      - carthage: SwipeCellKit
    postBuildScripts:
      - { path: "scripts/swiftlint.sh", name: Swiftlint }
    scheme:
      gatherCoverageData: true
    settings:
      base:
        APPLICATION_EXTENSION_API_ONLY: false
  OBAKitTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "12.4"
    sources: [OBAKitTests]
    dependencies:
      - target: App
      - carthage: Nimble
      - carthage: OHHTTPStubs