name: OBAKit
options:
  bundleIdPrefix: org.onebusaway
targets:
  DemoApp:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    sources: [DemoApp]
    dependencies:
      - target: OBAKit
      - carthage: SwiftProtobuf
  OBAKit:
    type: framework
    platform: iOS
    sources: [Application, Location, Models, Network]
    dependencies:
      - carthage: SwiftProtobuf