packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    majorVersion: 8.2.0

targets:
  App:
    dependencies:
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseCrashlytics
