############
# KiedyBus
############

options:
  bundleIdPrefix: pl.kiedybus

targets:
  App:
    sources: ["Apps/KiedyBus", "Apps/Shared/CommonClient"]
    entitlements:
      path: Apps/KiedyBus/KiedyBus.entitlements
      properties:
        com.apple.security.application-groups:
          - group.pl.kiedybus.iphone
    info:
      path: Apps/KiedyBus/Info.plist
      properties:
        CFBundleDisplayName: KiedyBus
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSExceptionDomains:
            goeuropa.eu:
              NSTemporaryExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
            kiedybus.pl:
              NSTemporaryExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
        NSHumanReadableCopyright: © goEuropa
        NSLocationAlwaysAndWhenInUseUsageDescription: Show your location on the map
        NSLocationWhenInUseUsageDescription: Show your location on the map
        NSUserActivityTypes:
          - pl.kiedybus.iphone.user_activity.stop
          - pl.kiedybus.iphone.user_activity.trip
        OBAKitConfig:
          AppDevelopersEmailAddress: info@goeuropa.eu
          AppGroup: group.pl.kiedybus.iphone
          BundledRegionsFileName: regions.json
          PrivacyPolicyURL: https://www.goeuropa.eu
          RESTServerAPIKey: web
          RegionsServerBaseAddress: https://kiedybus.pl
          RegionsServerAPIPath: /regions-v4.json
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: pl.kiedybus.iphone
        MARKETING_VERSION: 20.2.0
        
include:
  - path: Apps/Shared/app_shared.yml
  - path: Apps/Shared/analytics_fx_config.yml
  - path: OBAKitCore/project.yml
  - path: OBAKit/project.yml
  - path: OBAKitTests/project.yml