options:
  bundleIdPrefix: eu.goeuropa

targets:
  App:
    sources: ["Apps/KiedyBus"]
    dependencies:
      - framework: FIRAnalyticsConnector.framework
        embed: false
      - framework: FirebaseAnalytics.framework
        embed: false
      - framework: FirebaseCore.framework
        embed: false
      - framework: FirebaseCoreDiagnostics.framework
        embed: false
      - framework: FirebaseInstanceID.framework
        embed: false
      - framework: GoogleAppMeasurement.framework
        embed: false
      - framework: GoogleUtilities.framework
        embed: false
      - framework: nanopb.framework
        embed: false
      - framework: Fabric.framework
        embed: false
      - framework: Crashlytics.framework
        embed: false
    entitlements:
      path: Apps/KiedyBus/KiedyBus.entitlements
      properties:
        com.apple.security.application-groups:
          - group.eu.goeuropa.kiedybus
    info:
      path: Apps/KiedyBus/Info.plist
      properties:
        CFBundleDisplayName: KiedyBus
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSExceptionDomains:
            goeuropa.eu:
              NSTemporaryExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
            kiedybus.pl:
              NSTemporaryExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
        NSHumanReadableCopyright: © goEuropa
        NSLocationAlwaysAndWhenInUseUsageDescription: Show your location on the map
        NSLocationWhenInUseUsageDescription: Show your location on the map
        NSUserActivityTypes:
          - eu.goeuropa.kiedybus.user_activity.stop
          - eu.goeuropa.kiedybus.user_activity.trip
        OBAKitConfig:
          AppDevelopersEmailAddress: info@goeuropa.eu
          PrivacyPolicyURL: https://www.goeuropa.eu
          RESTServerAPIKey: web
          RegionsServerBaseAddress: https://kiedybus.pl
          RegionsServerAPIPath: /regions-v4.json
    postBuildScripts:
      - name: Crashlytics
        script: "${PROJECT_DIR}/Apps/Shared/Crashlytics/Fabric.framework/run"
        inputFiles: ["$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)"]
        runOnlyWhenInstalling: true
    settings:
      base:
        FRAMEWORK_SEARCH_PATHS: "$(inherited) $(PROJECT_DIR)/Apps/Shared/FirebaseAnalytics $(PROJECT_DIR)/Apps/Shared/Crashlytics"
        PRODUCT_BUNDLE_IDENTIFIER: eu.goeuropa.kiedybus
        MARKETING_VERSION: 20.2.0
        
include:
  - path: Apps/Shared/app_shared.yml
  - path: OBAKitCore/project.yml
  - path: OBAKit/project.yml
  - path: OBAKitTests/project.yml