name: OBAKit

############
# Options
############

settings:
  base:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true

options:
  minimumXcodeGenVersion: 2.10
  bundleIdPrefix: eu.goeuropa
  generateEmptyDirectories: true
  groupSortPosition: top
  deploymentTarget: 
    iOS: "12.4"

targets:
  App:
    type: application
    platform: iOS
    sources: ["Apps/KiedyBus"]
    dependencies:
      - target: OBAKitCore
      - target: OBAKit
      - carthage: SwiftProtobuf
      - framework: FIRAnalyticsConnector.framework
        embed: false
      - framework: FirebaseAnalytics.framework
        embed: false
      - framework: FirebaseCore.framework
        embed: false
      - framework: FirebaseCoreDiagnostics.framework
        embed: false
      - framework: FirebaseInstanceID.framework
        embed: false
      - framework: GoogleAppMeasurement.framework
        embed: false
      - framework: GoogleUtilities.framework
        embed: false
      - framework: nanopb.framework
        embed: false
      - framework: Fabric.framework
        embed: false
      - framework: Crashlytics.framework
        embed: false
    entitlements:
      path: Apps/KiedyBus/KiedyBus.entitlements
      properties:
        com.apple.security.application-groups:
          - group.eu.goeuropa.kiedybus
    preBuildScripts:
      - name: Versioning
        script: "${PROJECT_DIR}/scripts/version"
    postBuildScripts:
      - name: Crashlytics
        script: "${PROJECT_DIR}/Apps/Shared/Crashlytics/Fabric.framework/run"
        inputFiles: ["$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)"]
        runOnlyWhenInstalling: true
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: OBAKitTests
          parallelizable: true
          randomExecutionOrder: true
    settings:
      base:
        FRAMEWORK_SEARCH_PATHS: "$(inherited) $(PROJECT_DIR)/Apps/Shared/FirebaseAnalytics $(PROJECT_DIR)/Apps/Shared/Crashlytics"
        PRODUCT_BUNDLE_IDENTIFIER: eu.goeuropa.kiedybus
        OTHER_LDFLAGS: -ObjC
        MARKETING_VERSION: 20.2.0
        
include:
  - path: OBAKitCore/project.yml
  - path: OBAKit/project.yml
  - path: OBAKitTests/project.yml