targets:
  OBAKitTests:
    type: bundle.unit-test
    platform: iOS
    sources: ["."]
    dependencies:
      - target: App
      - carthage: Nimble
      - carthage: OHHTTPStubs
    info:
      path: "Info.plist"
      properties:
        NSPrincipalClass: OBAKitTests.OBAKitTestsSetup