options:
  bundleIdPrefix: ca.yrt

targets:
  App:
    sources:
      - path: Apps/YRTViva
        name: App
        group: YRTViva
      - path: Apps/Shared/CommonClient
        name: Common
        group: YRTViva
    entitlements:
      path: Apps/YRTViva/YRTViva.entitlements
      properties:
        com.apple.security.application-groups:
          - group.ca.yrt.YRTVIVA-iphone
    info:
      path: Apps/YRTViva/Info.plist
      properties:
        CFBundleDisplayName: YRTViva
        CFBundleURLTypes: [{CFBundleTypeRole: "Editor", CFBundleURLIconFile: "", CFBundleURLName: "yrtviva", CFBundleURLSchemes: ["yrtviva"]}]
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
        NSHumanReadableCopyright: © York Region Transit
        NSLocationAlwaysAndWhenInUseUsageDescription: Show your location on the map
        NSLocationWhenInUseUsageDescription: Show your location on the map
        NSUserActivityTypes:
          - ca.yrt.YRTVIVA-iphone.user_activity.stop
          - ca.yrt.YRTVIVA-iphone.user_activity.trip
        OBAKitConfig:
          AppDevelopersEmailAddress: transitinfo@york.ca
          AppGroup: group.ca.yrt.YRTVIVA-iphone
          BundledRegionsFileName: regions.json
          ExtensionURLScheme: yrtviva
          PrivacyPolicyURL: https://www.yrt.ca
          RESTServerAPIKey: test
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ca.yrt.YRTVIVA-iphone
        MARKETING_VERSION: 21.1.1
  TodayView:
    sources: ["Apps/YRTViva/Assets.xcassets"]
    entitlements:
      properties:
        com.apple.security.application-groups:
          - group.ca.yrt.YRTVIVA-iphone
    info:
      properties:
        CFBundleDisplayName: YRTViva
        CFBundleShortVersionString: 21.1.1
        OBAKitConfig:
          AppDevelopersEmailAddress: transitinfo@york.ca
          AppGroup: group.ca.yrt.YRTVIVA-iphone
          BundledRegionsFileName: regions.json
          ExtensionURLScheme: yrtviva
          PrivacyPolicyURL: https://www.yrt.ca
          RESTServerAPIKey: test
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ca.yrt.YRTVIVA-iphone.TodayView

include:
  - path: Apps/Shared/app_shared.yml
  - path: OBAKitCore/project.yml
  - path: OBAKit/project.yml
  - path: OBAKitTests/project.yml
  - path: OBAKitUITests/project.yml
  - path: TodayView/project.yml
