options:
  bundleIdPrefix: ca.yrt

targets:
  App:
    sources: ["Apps/YRTViva", "Apps/Shared/CommonClient"]
    dependencies:
      - framework: FIRAnalyticsConnector.framework
        embed: false
      - framework: FirebaseAnalytics.framework
        embed: false
      - framework: FirebaseCore.framework
        embed: false
      - framework: FirebaseCoreDiagnostics.framework
        embed: false
      - framework: FirebaseInstanceID.framework
        embed: false
      - framework: GoogleAppMeasurement.framework
        embed: false
      - framework: GoogleUtilities.framework
        embed: false
      - framework: nanopb.framework
        embed: false
      - framework: Fabric.framework
        embed: false
      - framework: Crashlytics.framework
        embed: false
    entitlements:
      path: Apps/YRTViva/YRTViva.entitlements
      properties:
        com.apple.security.application-groups:
          - group.ca.yrt.YRTVIVA-iphone
    info:
      path: Apps/YRTViva/Info.plist
      properties:
        CFBundleDisplayName: YRTViva
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
        NSHumanReadableCopyright: © York Region Transit
        NSLocationAlwaysAndWhenInUseUsageDescription: Show your location on the map
        NSLocationWhenInUseUsageDescription: Show your location on the map
        NSUserActivityTypes:
          - ca.yrt.YRTVIVA-iphone.user_activity.stop
          - ca.yrt.YRTVIVA-iphone.user_activity.trip
        OBAKitConfig:
          AppDevelopersEmailAddress: transitinfo@york.ca
          BundledRegionsFileName: regions.json
          PrivacyPolicyURL: https://www.yrt.ca
          RESTServerAPIKey: test
    postBuildScripts:
      - name: Crashlytics
        script: "${PROJECT_DIR}/Apps/Shared/Crashlytics/Fabric.framework/run"
        inputFiles: ["$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)"]
        runOnlyWhenInstalling: true
    settings:
      base:
        FRAMEWORK_SEARCH_PATHS: "$(inherited) $(PROJECT_DIR)/Apps/Shared/FirebaseAnalytics $(PROJECT_DIR)/Apps/Shared/Crashlytics"
        PRODUCT_BUNDLE_IDENTIFIER: ca.yrt.YRTVIVA-iphone
        MARKETING_VERSION: 20.2.0
        
include:
  - path: Apps/Shared/app_shared.yml
  - path: OBAKitCore/project.yml
  - path: OBAKit/project.yml
  - path: OBAKitTests/project.yml