targets:
  OBAKitCore:
    type: framework
    platform: iOS
    sources: ["."]
    dependencies:
      - carthage: CocoaLumberjack
      - carthage: CocoaLumberjackSwift
      - carthage: SwiftProtobuf
    scheme:
      gatherCoverageData: true
    info:
      path: "Info.plist"
      properties:
        CFBundleShortVersionString: 20.2.0
    settings:
      base:
        APPLICATION_EXTENSION_API_ONLY: true