name: OBAKitTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Switch Xcode 13
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app

    - name: Install xcodegen
      run: brew install xcodegen

    - name: Generate xcodeproj for OneBusAway
      run: scripts/generate_project OneBusAway

    # Build
    - name: Build OneBusAway
      run: xcodebuild clean build-for-testing
        -scheme 'App'
        -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 13'
        -quiet

    # Unit Test
    - name: OBAKit Unit Test
      run: xcodebuild test-without-building
        -only-testing:OBAKitTests
        -project 'OBAKit.xcodeproj'
        -scheme 'App'
        -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 13'
        -resultBundlePath OBAKitTests.xcresult
        -quiet

    # note 2021-10-22 (@ualch9): disabled for now, since there are no UI tests.
    # UI Test
    #- name: OBAKit UI Test
    #  run: xcodebuild test-without-building
    #    -only-testing:OBAKitUITests
    #    -project 'OBAKit.xcodeproj'
    #    -scheme 'App'
    #    -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 8'
    #    -resultBundlePath OBAKitUITests.xcresult
    #    -quiet
    
    # Upload results
    - uses: kishikawakatsumi/xcresulttool@v1.0.3
      if: ${{ success() || failure() }}
      with:
        path: |
          OBAKitTests.xcresult
    #      OBAKitUITests.xcresult # note 2021-10-22 (@ualch9): disabled for now, since there are no UI tests.

